version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: GangE
    environment:
      POSTGRES_DB: Dongo
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
